"""
Python 3 Interface of erl_gp_sdf
"""
from __future__ import annotations
import collections.abc
import erl_gaussian_process.pyerl_gaussian_process
import erl_geometry.pyerl_geometry
import numpy
import numpy.typing
import typing
__all__: list[str] = ['AbstractSurfaceMapping2Dd', 'AbstractSurfaceMapping2Df', 'AbstractSurfaceMapping3Dd', 'AbstractSurfaceMapping3Df', 'GpOccSurfaceMapping2Dd', 'GpOccSurfaceMapping2Df', 'GpOccSurfaceMapping3Dd', 'GpOccSurfaceMapping3Df', 'GpSdfMapping2Dd', 'GpSdfMapping2Df', 'GpSdfMapping3Dd', 'GpSdfMapping3Df', 'GpSdfMappingSetting2Dd', 'GpSdfMappingSetting2Df', 'GpSdfMappingSetting3Dd', 'GpSdfMappingSetting3Df', 'LogEdfGaussianProcessD', 'LogEdfGaussianProcessF', 'SdfGaussianProcessSettingD', 'SdfGaussianProcessSettingF', 'SdfGp2Dd', 'SdfGp2Df', 'SdfGp3Dd', 'SdfGp3Df', 'SignMethod', 'SurfaceData2Dd', 'SurfaceData2Df', 'SurfaceData3Dd', 'SurfaceData3Df', 'SurfaceDataManager2Dd', 'SurfaceDataManager2DdBase', 'SurfaceDataManager2Df', 'SurfaceDataManager2DfBase', 'SurfaceDataManager3Dd', 'SurfaceDataManager3DdBase', 'SurfaceDataManager3Df', 'SurfaceDataManager3DfBase', 'YamlableBase', 'kExternal', 'kHybrid', 'kNone', 'kNormalGp', 'kSignGp']
class AbstractSurfaceMapping2Dd:
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def create(mapping_type: str, setting: YamlableBase) -> AbstractSurfaceMapping2Dd:
        ...
    def __eq__(self, other: AbstractSurfaceMapping2Dd) -> bool:
        ...
    def __ne__(self, other: AbstractSurfaceMapping2Dd) -> bool:
        ...
    def read(self, filename: str) -> bool:
        ...
    def update(self, rotation: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 2]", "flags.f_contiguous"], translation: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 1]"], scan: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], are_points: bool, are_local: bool) -> bool:
        ...
    def write(self, filename: str) -> bool:
        ...
class AbstractSurfaceMapping2Df:
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def create(mapping_type: str, setting: YamlableBase) -> AbstractSurfaceMapping2Df:
        ...
    def __eq__(self, other: AbstractSurfaceMapping2Df) -> bool:
        ...
    def __ne__(self, other: AbstractSurfaceMapping2Df) -> bool:
        ...
    def read(self, filename: str) -> bool:
        ...
    def update(self, rotation: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[2, 2]", "flags.f_contiguous"], translation: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[2, 1]"], scan: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], are_points: bool, are_local: bool) -> bool:
        ...
    def write(self, filename: str) -> bool:
        ...
class AbstractSurfaceMapping3Dd:
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def create(mapping_type: str, setting: YamlableBase) -> AbstractSurfaceMapping3Dd:
        ...
    def __eq__(self, other: AbstractSurfaceMapping3Dd) -> bool:
        ...
    def __ne__(self, other: AbstractSurfaceMapping3Dd) -> bool:
        ...
    def read(self, filename: str) -> bool:
        ...
    def update(self, rotation: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 3]", "flags.f_contiguous"], translation: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"], scan: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], are_points: bool, are_local: bool) -> bool:
        ...
    def write(self, filename: str) -> bool:
        ...
class AbstractSurfaceMapping3Df:
    __hash__: typing.ClassVar[None] = None
    @staticmethod
    def create(mapping_type: str, setting: YamlableBase) -> AbstractSurfaceMapping3Df:
        ...
    def __eq__(self, other: AbstractSurfaceMapping3Df) -> bool:
        ...
    def __ne__(self, other: AbstractSurfaceMapping3Df) -> bool:
        ...
    def read(self, filename: str) -> bool:
        ...
    def update(self, rotation: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 3]", "flags.f_contiguous"], translation: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"], scan: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], are_points: bool, are_local: bool) -> bool:
        ...
    def write(self, filename: str) -> bool:
        ...
class GpOccSurfaceMapping2Dd(AbstractSurfaceMapping2Dd):
    class Setting(YamlableBase):
        class ComputeVariance:
            @property
            def max_distance_var(self) -> float:
                ...
            @max_distance_var.setter
            def max_distance_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def max_gradient_var(self) -> float:
                ...
            @max_gradient_var.setter
            def max_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def min_distance_var(self) -> float:
                ...
            @min_distance_var.setter
            def min_distance_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def min_gradient_var(self) -> float:
                ...
            @min_gradient_var.setter
            def min_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def position_var_alpha(self) -> float:
                ...
            @position_var_alpha.setter
            def position_var_alpha(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def zero_gradient_gradient_var(self) -> float:
                ...
            @zero_gradient_gradient_var.setter
            def zero_gradient_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def zero_gradient_position_var(self) -> float:
                ...
            @zero_gradient_position_var.setter
            def zero_gradient_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
        compute_variance: GpOccSurfaceMapping2Dd.Setting.ComputeVariance
        sensor_gp: erl_gaussian_process.pyerl_gaussian_process.LidarGaussianProcess2Dd.Setting
        tree: erl_geometry.pyerl_geometry.OccupancyQuadtreeBaseSetting
        update_map_points: GpOccSurfaceMapping2Dd.UpdateMapPoints
        update_occupancy: bool
        @property
        def cluster_depth(self) -> int:
            ...
        @cluster_depth.setter
        def cluster_depth(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def perturb_delta(self) -> float:
            ...
        @perturb_delta.setter
        def perturb_delta(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def scaling(self) -> float:
            ...
        @scaling.setter
        def scaling(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def zero_gradient_threshold(self) -> float:
            ...
        @zero_gradient_threshold.setter
        def zero_gradient_threshold(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    class UpdateMapPoints:
        @property
        def max_adjust_tries(self) -> int:
            ...
        @max_adjust_tries.setter
        def max_adjust_tries(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def max_bayes_gradient_var(self) -> float:
            ...
        @max_bayes_gradient_var.setter
        def max_bayes_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def max_bayes_position_var(self) -> float:
            ...
        @max_bayes_position_var.setter
        def max_bayes_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def max_surface_abs_occ(self) -> float:
            ...
        @max_surface_abs_occ.setter
        def max_surface_abs_occ(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def max_valid_gradient_var(self) -> float:
            ...
        @max_valid_gradient_var.setter
        def max_valid_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def min_gradient_var(self) -> float:
            ...
        @min_gradient_var.setter
        def min_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def min_observable_occ(self) -> float:
            ...
        @min_observable_occ.setter
        def min_observable_occ(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def min_position_var(self) -> float:
            ...
        @min_position_var.setter
        def min_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    def __init__(self, setting: GpOccSurfaceMapping2Dd.Setting) -> None:
        ...
    def collect_surface_data_in_aabb(self, aabb: erl_geometry.pyerl_geometry.Aabb2Dd) -> list[tuple[float, int]]:
        ...
    def get_cluster_center(self, cluster_key: erl_geometry.pyerl_geometry.QuadtreeKey) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 1]"]:
        ...
    def is_in_free_space(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, n]"]) -> tuple[bool, typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"]]:
        ...
    def read(self, filename: str) -> bool:
        ...
    def write(self, filename: str) -> bool:
        ...
    @property
    def changed_clusters(self) -> list[erl_geometry.pyerl_geometry.QuadtreeKey]:
        ...
    @property
    def cluster_size(self) -> float:
        ...
    @property
    def map_boundary(self) -> erl_geometry.pyerl_geometry.Aabb2Dd:
        ...
    @property
    def scaling(self) -> float:
        ...
    @property
    def sensor_gp(self) -> erl_gaussian_process.pyerl_gaussian_process.LidarGaussianProcess2Dd:
        ...
    @property
    def setting(self) -> GpOccSurfaceMapping2Dd.Setting:
        ...
    @property
    def surface_data_buffer(self) -> list[SurfaceData2Dd]:
        ...
    @property
    def surface_data_manager(self) -> SurfaceDataManager2Dd:
        ...
    @property
    def tree(self) -> erl_geometry.pyerl_geometry.OccupancyQuadtreeD:
        ...
class GpOccSurfaceMapping2Df(AbstractSurfaceMapping2Df):
    class Setting(YamlableBase):
        class ComputeVariance:
            @property
            def max_distance_var(self) -> float:
                ...
            @max_distance_var.setter
            def max_distance_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def max_gradient_var(self) -> float:
                ...
            @max_gradient_var.setter
            def max_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def min_distance_var(self) -> float:
                ...
            @min_distance_var.setter
            def min_distance_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def min_gradient_var(self) -> float:
                ...
            @min_gradient_var.setter
            def min_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def position_var_alpha(self) -> float:
                ...
            @position_var_alpha.setter
            def position_var_alpha(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def zero_gradient_gradient_var(self) -> float:
                ...
            @zero_gradient_gradient_var.setter
            def zero_gradient_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def zero_gradient_position_var(self) -> float:
                ...
            @zero_gradient_position_var.setter
            def zero_gradient_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
        compute_variance: GpOccSurfaceMapping2Df.Setting.ComputeVariance
        sensor_gp: erl_gaussian_process.pyerl_gaussian_process.LidarGaussianProcess2Df.Setting
        tree: erl_geometry.pyerl_geometry.OccupancyQuadtreeBaseSetting
        update_map_points: GpOccSurfaceMapping2Df.UpdateMapPoints
        update_occupancy: bool
        @property
        def cluster_depth(self) -> int:
            ...
        @cluster_depth.setter
        def cluster_depth(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def perturb_delta(self) -> float:
            ...
        @perturb_delta.setter
        def perturb_delta(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def scaling(self) -> float:
            ...
        @scaling.setter
        def scaling(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def zero_gradient_threshold(self) -> float:
            ...
        @zero_gradient_threshold.setter
        def zero_gradient_threshold(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    class UpdateMapPoints:
        @property
        def max_adjust_tries(self) -> int:
            ...
        @max_adjust_tries.setter
        def max_adjust_tries(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def max_bayes_gradient_var(self) -> float:
            ...
        @max_bayes_gradient_var.setter
        def max_bayes_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def max_bayes_position_var(self) -> float:
            ...
        @max_bayes_position_var.setter
        def max_bayes_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def max_surface_abs_occ(self) -> float:
            ...
        @max_surface_abs_occ.setter
        def max_surface_abs_occ(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def max_valid_gradient_var(self) -> float:
            ...
        @max_valid_gradient_var.setter
        def max_valid_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def min_gradient_var(self) -> float:
            ...
        @min_gradient_var.setter
        def min_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def min_observable_occ(self) -> float:
            ...
        @min_observable_occ.setter
        def min_observable_occ(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def min_position_var(self) -> float:
            ...
        @min_position_var.setter
        def min_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    def __init__(self, setting: GpOccSurfaceMapping2Df.Setting) -> None:
        ...
    def collect_surface_data_in_aabb(self, aabb: erl_geometry.pyerl_geometry.Aabb2Df) -> list[tuple[float, int]]:
        ...
    def get_cluster_center(self, cluster_key: erl_geometry.pyerl_geometry.QuadtreeKey) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[2, 1]"]:
        ...
    def is_in_free_space(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, n]"]) -> tuple[bool, typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"]]:
        ...
    def read(self, filename: str) -> bool:
        ...
    def write(self, filename: str) -> bool:
        ...
    @property
    def changed_clusters(self) -> list[erl_geometry.pyerl_geometry.QuadtreeKey]:
        ...
    @property
    def cluster_size(self) -> float:
        ...
    @property
    def map_boundary(self) -> erl_geometry.pyerl_geometry.Aabb2Df:
        ...
    @property
    def scaling(self) -> float:
        ...
    @property
    def sensor_gp(self) -> erl_gaussian_process.pyerl_gaussian_process.LidarGaussianProcess2Df:
        ...
    @property
    def setting(self) -> GpOccSurfaceMapping2Df.Setting:
        ...
    @property
    def surface_data_buffer(self) -> list[SurfaceData2Df]:
        ...
    @property
    def surface_data_manager(self) -> SurfaceDataManager2Df:
        ...
    @property
    def tree(self) -> erl_geometry.pyerl_geometry.OccupancyQuadtreeF:
        ...
class GpOccSurfaceMapping3Dd(AbstractSurfaceMapping3Dd):
    class Setting(YamlableBase):
        class ComputeVariance:
            @property
            def max_distance_var(self) -> float:
                ...
            @max_distance_var.setter
            def max_distance_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def max_gradient_var(self) -> float:
                ...
            @max_gradient_var.setter
            def max_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def min_distance_var(self) -> float:
                ...
            @min_distance_var.setter
            def min_distance_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def min_gradient_var(self) -> float:
                ...
            @min_gradient_var.setter
            def min_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def position_var_alpha(self) -> float:
                ...
            @position_var_alpha.setter
            def position_var_alpha(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def zero_gradient_gradient_var(self) -> float:
                ...
            @zero_gradient_gradient_var.setter
            def zero_gradient_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def zero_gradient_position_var(self) -> float:
                ...
            @zero_gradient_position_var.setter
            def zero_gradient_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
        compute_variance: GpOccSurfaceMapping3Dd.Setting.ComputeVariance
        sensor_gp: erl_gaussian_process.pyerl_gaussian_process.RangeSensorGaussianProcess3Dd.Setting
        tree: erl_geometry.pyerl_geometry.OccupancyOctreeBaseSetting
        update_map_points: GpOccSurfaceMapping3Dd.UpdateMapPoints
        update_occupancy: bool
        @property
        def cluster_depth(self) -> int:
            ...
        @cluster_depth.setter
        def cluster_depth(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def perturb_delta(self) -> float:
            ...
        @perturb_delta.setter
        def perturb_delta(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def scaling(self) -> float:
            ...
        @scaling.setter
        def scaling(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def zero_gradient_threshold(self) -> float:
            ...
        @zero_gradient_threshold.setter
        def zero_gradient_threshold(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    class UpdateMapPoints:
        @property
        def max_adjust_tries(self) -> int:
            ...
        @max_adjust_tries.setter
        def max_adjust_tries(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def max_bayes_gradient_var(self) -> float:
            ...
        @max_bayes_gradient_var.setter
        def max_bayes_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def max_bayes_position_var(self) -> float:
            ...
        @max_bayes_position_var.setter
        def max_bayes_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def max_surface_abs_occ(self) -> float:
            ...
        @max_surface_abs_occ.setter
        def max_surface_abs_occ(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def max_valid_gradient_var(self) -> float:
            ...
        @max_valid_gradient_var.setter
        def max_valid_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def min_gradient_var(self) -> float:
            ...
        @min_gradient_var.setter
        def min_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def min_observable_occ(self) -> float:
            ...
        @min_observable_occ.setter
        def min_observable_occ(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def min_position_var(self) -> float:
            ...
        @min_position_var.setter
        def min_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    def __init__(self, setting: GpOccSurfaceMapping3Dd.Setting) -> None:
        ...
    def collect_surface_data_in_aabb(self, aabb: erl_geometry.pyerl_geometry.Aabb3Dd) -> list[tuple[float, int]]:
        ...
    def get_cluster_center(self, cluster_key: erl_geometry.pyerl_geometry.OctreeKey) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    def is_in_free_space(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, n]"]) -> tuple[bool, typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"]]:
        ...
    def read(self, filename: str) -> bool:
        ...
    def write(self, filename: str) -> bool:
        ...
    @property
    def changed_clusters(self) -> list[erl_geometry.pyerl_geometry.OctreeKey]:
        ...
    @property
    def cluster_size(self) -> float:
        ...
    @property
    def map_boundary(self) -> erl_geometry.pyerl_geometry.Aabb3Dd:
        ...
    @property
    def scaling(self) -> float:
        ...
    @property
    def sensor_gp(self) -> erl_gaussian_process.pyerl_gaussian_process.RangeSensorGaussianProcess3Dd:
        ...
    @property
    def setting(self) -> GpOccSurfaceMapping3Dd.Setting:
        ...
    @property
    def surface_data_buffer(self) -> list[SurfaceData3Dd]:
        ...
    @property
    def surface_data_manager(self) -> SurfaceDataManager3Dd:
        ...
    @property
    def tree(self) -> erl_geometry.pyerl_geometry.OccupancyOctreeD:
        ...
class GpOccSurfaceMapping3Df(AbstractSurfaceMapping3Df):
    class Setting(YamlableBase):
        class ComputeVariance:
            @property
            def max_distance_var(self) -> float:
                ...
            @max_distance_var.setter
            def max_distance_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def max_gradient_var(self) -> float:
                ...
            @max_gradient_var.setter
            def max_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def min_distance_var(self) -> float:
                ...
            @min_distance_var.setter
            def min_distance_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def min_gradient_var(self) -> float:
                ...
            @min_gradient_var.setter
            def min_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def position_var_alpha(self) -> float:
                ...
            @position_var_alpha.setter
            def position_var_alpha(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def zero_gradient_gradient_var(self) -> float:
                ...
            @zero_gradient_gradient_var.setter
            def zero_gradient_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
            @property
            def zero_gradient_position_var(self) -> float:
                ...
            @zero_gradient_position_var.setter
            def zero_gradient_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
                ...
        compute_variance: GpOccSurfaceMapping3Df.Setting.ComputeVariance
        sensor_gp: erl_gaussian_process.pyerl_gaussian_process.RangeSensorGaussianProcess3Df.Setting
        tree: erl_geometry.pyerl_geometry.OccupancyOctreeBaseSetting
        update_map_points: GpOccSurfaceMapping3Df.UpdateMapPoints
        update_occupancy: bool
        @property
        def cluster_depth(self) -> int:
            ...
        @cluster_depth.setter
        def cluster_depth(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def perturb_delta(self) -> float:
            ...
        @perturb_delta.setter
        def perturb_delta(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def scaling(self) -> float:
            ...
        @scaling.setter
        def scaling(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def zero_gradient_threshold(self) -> float:
            ...
        @zero_gradient_threshold.setter
        def zero_gradient_threshold(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    class UpdateMapPoints:
        @property
        def max_adjust_tries(self) -> int:
            ...
        @max_adjust_tries.setter
        def max_adjust_tries(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def max_bayes_gradient_var(self) -> float:
            ...
        @max_bayes_gradient_var.setter
        def max_bayes_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def max_bayes_position_var(self) -> float:
            ...
        @max_bayes_position_var.setter
        def max_bayes_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def max_surface_abs_occ(self) -> float:
            ...
        @max_surface_abs_occ.setter
        def max_surface_abs_occ(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def max_valid_gradient_var(self) -> float:
            ...
        @max_valid_gradient_var.setter
        def max_valid_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def min_gradient_var(self) -> float:
            ...
        @min_gradient_var.setter
        def min_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def min_observable_occ(self) -> float:
            ...
        @min_observable_occ.setter
        def min_observable_occ(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def min_position_var(self) -> float:
            ...
        @min_position_var.setter
        def min_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    def __init__(self, setting: GpOccSurfaceMapping3Df.Setting) -> None:
        ...
    def collect_surface_data_in_aabb(self, aabb: erl_geometry.pyerl_geometry.Aabb3Df) -> list[tuple[float, int]]:
        ...
    def get_cluster_center(self, cluster_key: erl_geometry.pyerl_geometry.OctreeKey) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"]:
        ...
    def is_in_free_space(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, n]"]) -> tuple[bool, typing.Annotated[numpy.typing.NDArray[numpy.bool], "[m, 1]"]]:
        ...
    def read(self, filename: str) -> bool:
        ...
    def write(self, filename: str) -> bool:
        ...
    @property
    def changed_clusters(self) -> list[erl_geometry.pyerl_geometry.OctreeKey]:
        ...
    @property
    def cluster_size(self) -> float:
        ...
    @property
    def map_boundary(self) -> erl_geometry.pyerl_geometry.Aabb3Df:
        ...
    @property
    def scaling(self) -> float:
        ...
    @property
    def sensor_gp(self) -> erl_gaussian_process.pyerl_gaussian_process.RangeSensorGaussianProcess3Df:
        ...
    @property
    def setting(self) -> GpOccSurfaceMapping3Df.Setting:
        ...
    @property
    def surface_data_buffer(self) -> list[SurfaceData3Df]:
        ...
    @property
    def surface_data_manager(self) -> SurfaceDataManager3Df:
        ...
    @property
    def tree(self) -> erl_geometry.pyerl_geometry.OccupancyOctreeF:
        ...
class GpSdfMapping2Dd:
    def __init__(self, setting: GpSdfMappingSetting2Dd, surface_mapping: AbstractSurfaceMapping2Dd) -> None:
        ...
    def test(self, positions: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, n]", "flags.f_contiguous"]) -> dict | None:
        ...
    def update_gp_sdf(self, time_budget_us: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    @property
    def gps(self) -> ...:
        ...
    @property
    def setting(self) -> GpSdfMappingSetting2Dd:
        ...
    @property
    def used_gps(self) -> list[typing.Annotated[list[SdfGp2Dd], "FixedSize(2)"]]:
        """
        GPs used by the last test call
        """
class GpSdfMapping2Df:
    def __init__(self, setting: GpSdfMappingSetting2Df, surface_mapping: AbstractSurfaceMapping2Df) -> None:
        ...
    def test(self, positions: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[2, n]", "flags.f_contiguous"]) -> dict | None:
        ...
    def update_gp_sdf(self, time_budget_us: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    @property
    def gps(self) -> ...:
        ...
    @property
    def setting(self) -> GpSdfMappingSetting2Df:
        ...
    @property
    def used_gps(self) -> list[typing.Annotated[list[SdfGp2Df], "FixedSize(2)"]]:
        """
        GPs used by the last test call
        """
class GpSdfMapping3Dd:
    def __init__(self, setting: GpSdfMappingSetting3Dd, surface_mapping: AbstractSurfaceMapping3Dd) -> None:
        ...
    def test(self, positions: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, n]", "flags.f_contiguous"]) -> dict | None:
        ...
    def update_gp_sdf(self, time_budget_us: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    @property
    def gps(self) -> ...:
        ...
    @property
    def setting(self) -> GpSdfMappingSetting3Dd:
        ...
    @property
    def used_gps(self) -> list[typing.Annotated[list[SdfGp3Dd], "FixedSize(4)"]]:
        """
        GPs used by the last test call
        """
class GpSdfMapping3Df:
    def __init__(self, setting: GpSdfMappingSetting3Df, surface_mapping: AbstractSurfaceMapping3Df) -> None:
        ...
    def test(self, positions: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, n]", "flags.f_contiguous"]) -> dict | None:
        ...
    def update_gp_sdf(self, time_budget_us: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    @property
    def gps(self) -> ...:
        ...
    @property
    def setting(self) -> GpSdfMappingSetting3Df:
        ...
    @property
    def used_gps(self) -> list[typing.Annotated[list[SdfGp3Df], "FixedSize(4)"]]:
        """
        GPs used by the last test call
        """
class GpSdfMappingSetting2Dd(YamlableBase):
    class TestQuery:
        compute_covariance: bool
        compute_gradient: bool
        compute_gradient_variance: bool
        retrain_outdated: bool
        use_global_buffer: bool
        use_gp_covariance: bool
        use_smallest: bool
        @property
        def max_test_valid_distance_var(self) -> float:
            ...
        @max_test_valid_distance_var.setter
        def max_test_valid_distance_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def num_neighbor_gps(self) -> int:
            ...
        @num_neighbor_gps.setter
        def num_neighbor_gps(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def search_area_half_size(self) -> float:
            ...
        @search_area_half_size.setter
        def search_area_half_size(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    sdf_gp: SdfGaussianProcessSettingD
    test_query: GpSdfMappingSetting2Dd.TestQuery
    def __init__(self) -> None:
        ...
    @property
    def gp_sdf_area_scale(self) -> float:
        ...
    @gp_sdf_area_scale.setter
    def gp_sdf_area_scale(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def invalid_position_var(self) -> float:
        ...
    @invalid_position_var.setter
    def invalid_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def max_valid_gradient_var(self) -> float:
        ...
    @max_valid_gradient_var.setter
    def max_valid_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def num_threads(self) -> int:
        ...
    @num_threads.setter
    def num_threads(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def sensor_noise(self) -> float:
        ...
    @sensor_noise.setter
    def sensor_noise(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def update_hz(self) -> float:
        ...
    @update_hz.setter
    def update_hz(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class GpSdfMappingSetting2Df(YamlableBase):
    class TestQuery:
        compute_covariance: bool
        compute_gradient: bool
        compute_gradient_variance: bool
        retrain_outdated: bool
        use_global_buffer: bool
        use_gp_covariance: bool
        use_smallest: bool
        @property
        def max_test_valid_distance_var(self) -> float:
            ...
        @max_test_valid_distance_var.setter
        def max_test_valid_distance_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def num_neighbor_gps(self) -> int:
            ...
        @num_neighbor_gps.setter
        def num_neighbor_gps(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def search_area_half_size(self) -> float:
            ...
        @search_area_half_size.setter
        def search_area_half_size(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    sdf_gp: SdfGaussianProcessSettingF
    test_query: GpSdfMappingSetting2Df.TestQuery
    def __init__(self) -> None:
        ...
    @property
    def gp_sdf_area_scale(self) -> float:
        ...
    @gp_sdf_area_scale.setter
    def gp_sdf_area_scale(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def invalid_position_var(self) -> float:
        ...
    @invalid_position_var.setter
    def invalid_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def max_valid_gradient_var(self) -> float:
        ...
    @max_valid_gradient_var.setter
    def max_valid_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def num_threads(self) -> int:
        ...
    @num_threads.setter
    def num_threads(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def sensor_noise(self) -> float:
        ...
    @sensor_noise.setter
    def sensor_noise(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def update_hz(self) -> float:
        ...
    @update_hz.setter
    def update_hz(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class GpSdfMappingSetting3Dd(YamlableBase):
    class TestQuery:
        compute_covariance: bool
        compute_gradient: bool
        compute_gradient_variance: bool
        retrain_outdated: bool
        use_global_buffer: bool
        use_gp_covariance: bool
        use_smallest: bool
        @property
        def max_test_valid_distance_var(self) -> float:
            ...
        @max_test_valid_distance_var.setter
        def max_test_valid_distance_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def num_neighbor_gps(self) -> int:
            ...
        @num_neighbor_gps.setter
        def num_neighbor_gps(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def search_area_half_size(self) -> float:
            ...
        @search_area_half_size.setter
        def search_area_half_size(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    sdf_gp: SdfGaussianProcessSettingD
    test_query: GpSdfMappingSetting3Dd.TestQuery
    def __init__(self) -> None:
        ...
    @property
    def gp_sdf_area_scale(self) -> float:
        ...
    @gp_sdf_area_scale.setter
    def gp_sdf_area_scale(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def invalid_position_var(self) -> float:
        ...
    @invalid_position_var.setter
    def invalid_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def max_valid_gradient_var(self) -> float:
        ...
    @max_valid_gradient_var.setter
    def max_valid_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def num_threads(self) -> int:
        ...
    @num_threads.setter
    def num_threads(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def sensor_noise(self) -> float:
        ...
    @sensor_noise.setter
    def sensor_noise(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def update_hz(self) -> float:
        ...
    @update_hz.setter
    def update_hz(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class GpSdfMappingSetting3Df(YamlableBase):
    class TestQuery:
        compute_covariance: bool
        compute_gradient: bool
        compute_gradient_variance: bool
        retrain_outdated: bool
        use_global_buffer: bool
        use_gp_covariance: bool
        use_smallest: bool
        @property
        def max_test_valid_distance_var(self) -> float:
            ...
        @max_test_valid_distance_var.setter
        def max_test_valid_distance_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
        @property
        def num_neighbor_gps(self) -> int:
            ...
        @num_neighbor_gps.setter
        def num_neighbor_gps(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
            ...
        @property
        def search_area_half_size(self) -> float:
            ...
        @search_area_half_size.setter
        def search_area_half_size(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    sdf_gp: SdfGaussianProcessSettingF
    test_query: GpSdfMappingSetting3Df.TestQuery
    def __init__(self) -> None:
        ...
    @property
    def gp_sdf_area_scale(self) -> float:
        ...
    @gp_sdf_area_scale.setter
    def gp_sdf_area_scale(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def invalid_position_var(self) -> float:
        ...
    @invalid_position_var.setter
    def invalid_position_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def max_valid_gradient_var(self) -> float:
        ...
    @max_valid_gradient_var.setter
    def max_valid_gradient_var(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def num_threads(self) -> int:
        ...
    @num_threads.setter
    def num_threads(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def sensor_noise(self) -> float:
        ...
    @sensor_noise.setter
    def sensor_noise(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def update_hz(self) -> float:
        ...
    @update_hz.setter
    def update_hz(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class LogEdfGaussianProcessD(erl_gaussian_process.pyerl_gaussian_process.NoisyInputGaussianProcessD):
    class Setting(erl_gaussian_process.pyerl_gaussian_process.NoisyInputGaussianProcessD.Setting):
        def __init__(self) -> None:
            ...
        @property
        def log_lambda(self) -> float:
            ...
        @log_lambda.setter
        def log_lambda(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    class TestResult(erl_gaussian_process.pyerl_gaussian_process.NoisyInputGaussianProcessD.TestResult):
        def get_gradient_2d(self, index: typing.SupportsInt | typing.SupportsIndex, y_index: typing.SupportsInt | typing.SupportsIndex) -> tuple[bool, typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 1]"]]:
            ...
        def get_gradient_3d(self, index: typing.SupportsInt | typing.SupportsIndex, y_index: typing.SupportsInt | typing.SupportsIndex) -> tuple[bool, typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]]:
            ...
    def __init__(self, setting: LogEdfGaussianProcessD.Setting) -> None:
        ...
    def load_surface_data_2d(self, surface_data_indices: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]], surface_data_vec: collections.abc.Sequence[SurfaceData2Dd], coord_origin: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"], data_sorted: bool, load_normals: bool, normal_scale: typing.SupportsFloat | typing.SupportsIndex, offset_distance: typing.SupportsFloat | typing.SupportsIndex, sensor_noise: typing.SupportsFloat | typing.SupportsIndex, max_valid_gradient_var: typing.SupportsFloat | typing.SupportsIndex, invalid_position_var: typing.SupportsFloat | typing.SupportsIndex) -> int:
        ...
    def load_surface_data_3d(self, surface_data_indices: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]], surface_data_vec: collections.abc.Sequence[SurfaceData3Dd], coord_origin: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], data_sorted: bool, load_normals: bool, normal_scale: typing.SupportsFloat | typing.SupportsIndex, offset_distance: typing.SupportsFloat | typing.SupportsIndex, sensor_noise: typing.SupportsFloat | typing.SupportsIndex, max_valid_gradient_var: typing.SupportsFloat | typing.SupportsIndex, invalid_position_var: typing.SupportsFloat | typing.SupportsIndex) -> int:
        ...
    def test(self, mat_x_test: typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, n]", "flags.f_contiguous"], predict_gradient: bool) -> erl_gaussian_process.pyerl_gaussian_process.NoisyInputGaussianProcessD.TestResult:
        ...
    @property
    def memory_usage(self) -> int:
        ...
    @property
    def setting(self) -> LogEdfGaussianProcessD.Setting:
        ...
class LogEdfGaussianProcessF(erl_gaussian_process.pyerl_gaussian_process.NoisyInputGaussianProcessF):
    class Setting(erl_gaussian_process.pyerl_gaussian_process.NoisyInputGaussianProcessF.Setting):
        def __init__(self) -> None:
            ...
        @property
        def log_lambda(self) -> float:
            ...
        @log_lambda.setter
        def log_lambda(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
            ...
    class TestResult(erl_gaussian_process.pyerl_gaussian_process.NoisyInputGaussianProcessF.TestResult):
        def get_gradient_2d(self, index: typing.SupportsInt | typing.SupportsIndex, y_index: typing.SupportsInt | typing.SupportsIndex) -> tuple[bool, typing.Annotated[numpy.typing.NDArray[numpy.float32], "[2, 1]"]]:
            ...
        def get_gradient_3d(self, index: typing.SupportsInt | typing.SupportsIndex, y_index: typing.SupportsInt | typing.SupportsIndex) -> tuple[bool, typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"]]:
            ...
    def __init__(self, setting: LogEdfGaussianProcessF.Setting) -> None:
        ...
    def load_surface_data_2d(self, surface_data_indices: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]], surface_data_vec: collections.abc.Sequence[SurfaceData2Df], coord_origin: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"], data_sorted: bool, load_normals: bool, normal_scale: typing.SupportsFloat | typing.SupportsIndex, offset_distance: typing.SupportsFloat | typing.SupportsIndex, sensor_noise: typing.SupportsFloat | typing.SupportsIndex, max_valid_gradient_var: typing.SupportsFloat | typing.SupportsIndex, invalid_position_var: typing.SupportsFloat | typing.SupportsIndex) -> int:
        ...
    def load_surface_data_3d(self, surface_data_indices: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]], surface_data_vec: collections.abc.Sequence[SurfaceData3Df], coord_origin: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"], data_sorted: bool, load_normals: bool, normal_scale: typing.SupportsFloat | typing.SupportsIndex, offset_distance: typing.SupportsFloat | typing.SupportsIndex, sensor_noise: typing.SupportsFloat | typing.SupportsIndex, max_valid_gradient_var: typing.SupportsFloat | typing.SupportsIndex, invalid_position_var: typing.SupportsFloat | typing.SupportsIndex) -> int:
        ...
    def test(self, mat_x_test: typing.Annotated[numpy.typing.NDArray[numpy.float32], "[m, n]", "flags.f_contiguous"], predict_gradient: bool) -> erl_gaussian_process.pyerl_gaussian_process.NoisyInputGaussianProcessF.TestResult:
        ...
    @property
    def memory_usage(self) -> int:
        ...
    @property
    def setting(self) -> LogEdfGaussianProcessF.Setting:
        ...
class SdfGaussianProcessSettingD(YamlableBase):
    edf_gp: LogEdfGaussianProcessD.Setting
    hybrid_sign_methods: tuple[SignMethod, SignMethod]
    sign_gp: erl_gaussian_process.pyerl_gaussian_process.NoisyInputGaussianProcessD.Setting
    sign_method: SignMethod
    @property
    def edf_gp_offset_distance(self) -> float:
        ...
    @edf_gp_offset_distance.setter
    def edf_gp_offset_distance(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def hybrid_sign_threshold(self) -> float:
        ...
    @hybrid_sign_threshold.setter
    def hybrid_sign_threshold(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def normal_scale(self) -> float:
        ...
    @normal_scale.setter
    def normal_scale(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def sign_gp_offset_distance(self) -> float:
        ...
    @sign_gp_offset_distance.setter
    def sign_gp_offset_distance(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def softmin_temperature(self) -> float:
        ...
    @softmin_temperature.setter
    def softmin_temperature(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class SdfGaussianProcessSettingF(YamlableBase):
    edf_gp: LogEdfGaussianProcessF.Setting
    hybrid_sign_methods: tuple[SignMethod, SignMethod]
    sign_gp: erl_gaussian_process.pyerl_gaussian_process.NoisyInputGaussianProcessF.Setting
    sign_method: SignMethod
    @property
    def edf_gp_offset_distance(self) -> float:
        ...
    @edf_gp_offset_distance.setter
    def edf_gp_offset_distance(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def hybrid_sign_threshold(self) -> float:
        ...
    @hybrid_sign_threshold.setter
    def hybrid_sign_threshold(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def normal_scale(self) -> float:
        ...
    @normal_scale.setter
    def normal_scale(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def sign_gp_offset_distance(self) -> float:
        ...
    @sign_gp_offset_distance.setter
    def sign_gp_offset_distance(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def softmin_temperature(self) -> float:
        ...
    @softmin_temperature.setter
    def softmin_temperature(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class SdfGp2Dd:
    setting: SdfGaussianProcessSettingD
    def activate(self) -> None:
        ...
    def deactivate(self) -> None:
        ...
    @typing.overload
    def intersects(self, other_position: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"], other_half_size: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    @typing.overload
    def intersects(self, other_position: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"], other_half_sizes: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"]) -> bool:
        ...
    def load_surface_data(self, surface_data_indices: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]], surface_data_vec: collections.abc.Sequence[SurfaceData2Dd], data_sorted: bool, sensor_noise: typing.SupportsFloat | typing.SupportsIndex, max_valid_gradient_var: typing.SupportsFloat | typing.SupportsIndex, invalid_position_var: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    def mark_buffer_outdated(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def mark_gp_outdated(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def mark_queried(self) -> None:
        ...
    def test(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"], arg1: typing.SupportsFloat | typing.SupportsIndex, arg2: bool, arg3: bool, arg4: bool, arg5: bool) -> tuple:
        ...
    def train(self) -> None:
        ...
    @property
    def active(self) -> bool:
        ...
    @property
    def buffer_outdated(self) -> bool:
        ...
    @property
    def edf_gp(self) -> LogEdfGaussianProcessD:
        ...
    @property
    def half_size(self) -> float:
        ...
    @property
    def is_trained(self) -> bool:
        ...
    @property
    def memory_usage(self) -> int:
        ...
    @property
    def position(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 1]"]:
        ...
    @property
    def sign_gp(self) -> ...:
        ...
    @property
    def time_stamp(self) -> int:
        ...
    @property
    def use_normal_gp(self) -> bool:
        ...
class SdfGp2Df:
    setting: SdfGaussianProcessSettingF
    def activate(self) -> None:
        ...
    def deactivate(self) -> None:
        ...
    @typing.overload
    def intersects(self, other_position: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"], other_half_size: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    @typing.overload
    def intersects(self, other_position: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"], other_half_sizes: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"]) -> bool:
        ...
    def load_surface_data(self, surface_data_indices: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]], surface_data_vec: collections.abc.Sequence[SurfaceData2Df], data_sorted: bool, sensor_noise: typing.SupportsFloat | typing.SupportsIndex, max_valid_gradient_var: typing.SupportsFloat | typing.SupportsIndex, invalid_position_var: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    def mark_buffer_outdated(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def mark_gp_outdated(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def mark_queried(self) -> None:
        ...
    def test(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"], arg1: typing.SupportsFloat | typing.SupportsIndex, arg2: bool, arg3: bool, arg4: bool, arg5: bool) -> tuple:
        ...
    def train(self) -> None:
        ...
    @property
    def active(self) -> bool:
        ...
    @property
    def buffer_outdated(self) -> bool:
        ...
    @property
    def edf_gp(self) -> LogEdfGaussianProcessF:
        ...
    @property
    def half_size(self) -> float:
        ...
    @property
    def is_trained(self) -> bool:
        ...
    @property
    def memory_usage(self) -> int:
        ...
    @property
    def position(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[2, 1]"]:
        ...
    @property
    def sign_gp(self) -> ...:
        ...
    @property
    def time_stamp(self) -> int:
        ...
    @property
    def use_normal_gp(self) -> bool:
        ...
class SdfGp3Dd:
    setting: SdfGaussianProcessSettingD
    def activate(self) -> None:
        ...
    def deactivate(self) -> None:
        ...
    @typing.overload
    def intersects(self, other_position: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], other_half_size: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    @typing.overload
    def intersects(self, other_position: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], other_half_sizes: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> bool:
        ...
    def load_surface_data(self, surface_data_indices: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]], surface_data_vec: collections.abc.Sequence[SurfaceData3Dd], data_sorted: bool, sensor_noise: typing.SupportsFloat | typing.SupportsIndex, max_valid_gradient_var: typing.SupportsFloat | typing.SupportsIndex, invalid_position_var: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    def mark_buffer_outdated(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def mark_gp_outdated(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def mark_queried(self) -> None:
        ...
    def test(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], arg1: typing.SupportsFloat | typing.SupportsIndex, arg2: bool, arg3: bool, arg4: bool, arg5: bool) -> tuple:
        ...
    def train(self) -> None:
        ...
    @property
    def active(self) -> bool:
        ...
    @property
    def buffer_outdated(self) -> bool:
        ...
    @property
    def edf_gp(self) -> LogEdfGaussianProcessD:
        ...
    @property
    def half_size(self) -> float:
        ...
    @property
    def is_trained(self) -> bool:
        ...
    @property
    def memory_usage(self) -> int:
        ...
    @property
    def position(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @property
    def sign_gp(self) -> ...:
        ...
    @property
    def time_stamp(self) -> int:
        ...
    @property
    def use_normal_gp(self) -> bool:
        ...
class SdfGp3Df:
    setting: SdfGaussianProcessSettingF
    def activate(self) -> None:
        ...
    def deactivate(self) -> None:
        ...
    @typing.overload
    def intersects(self, other_position: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"], other_half_size: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    @typing.overload
    def intersects(self, other_position: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"], other_half_sizes: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"]) -> bool:
        ...
    def load_surface_data(self, surface_data_indices: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex]], surface_data_vec: collections.abc.Sequence[SurfaceData3Df], data_sorted: bool, sensor_noise: typing.SupportsFloat | typing.SupportsIndex, max_valid_gradient_var: typing.SupportsFloat | typing.SupportsIndex, invalid_position_var: typing.SupportsFloat | typing.SupportsIndex) -> bool:
        ...
    def mark_buffer_outdated(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def mark_gp_outdated(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def mark_queried(self) -> None:
        ...
    def test(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"], arg1: typing.SupportsFloat | typing.SupportsIndex, arg2: bool, arg3: bool, arg4: bool, arg5: bool) -> tuple:
        ...
    def train(self) -> None:
        ...
    @property
    def active(self) -> bool:
        ...
    @property
    def buffer_outdated(self) -> bool:
        ...
    @property
    def edf_gp(self) -> LogEdfGaussianProcessF:
        ...
    @property
    def half_size(self) -> float:
        ...
    @property
    def is_trained(self) -> bool:
        ...
    @property
    def memory_usage(self) -> int:
        ...
    @property
    def position(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"]:
        ...
    @property
    def sign_gp(self) -> ...:
        ...
    @property
    def time_stamp(self) -> int:
        ...
    @property
    def use_normal_gp(self) -> bool:
        ...
class SignMethod:
    """
    Members:
    
      kNone
    
      kSignGp
    
      kNormalGp
    
      kExternal
    
      kHybrid
    """
    __members__: typing.ClassVar[dict[str, SignMethod]]  # value = {'kNone': <SignMethod.kNone: 0>, 'kSignGp': <SignMethod.kSignGp: 1>, 'kNormalGp': <SignMethod.kNormalGp: 2>, 'kExternal': <SignMethod.kExternal: 3>, 'kHybrid': <SignMethod.kHybrid: 4>}
    kExternal: typing.ClassVar[SignMethod]  # value = <SignMethod.kExternal: 3>
    kHybrid: typing.ClassVar[SignMethod]  # value = <SignMethod.kHybrid: 4>
    kNone: typing.ClassVar[SignMethod]  # value = <SignMethod.kNone: 0>
    kNormalGp: typing.ClassVar[SignMethod]  # value = <SignMethod.kNormalGp: 2>
    kSignGp: typing.ClassVar[SignMethod]  # value = <SignMethod.kSignGp: 1>
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class SurfaceData2Dd:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, position: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"], normal: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"], var_position: typing.SupportsFloat | typing.SupportsIndex, var_normal: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def normal(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 1]"]:
        ...
    @normal.setter
    def normal(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"]) -> None:
        ...
    @property
    def position(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[2, 1]"]:
        ...
    @position.setter
    def position(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"]) -> None:
        ...
    @property
    def var_normal(self) -> float:
        ...
    @var_normal.setter
    def var_normal(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def var_position(self) -> float:
        ...
    @var_position.setter
    def var_position(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class SurfaceData2Df:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, position: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"], normal: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"], var_position: typing.SupportsFloat | typing.SupportsIndex, var_normal: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def normal(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[2, 1]"]:
        ...
    @normal.setter
    def normal(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"]) -> None:
        ...
    @property
    def position(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[2, 1]"]:
        ...
    @position.setter
    def position(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[2, 1]"]) -> None:
        ...
    @property
    def var_normal(self) -> float:
        ...
    @var_normal.setter
    def var_normal(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def var_position(self) -> float:
        ...
    @var_position.setter
    def var_position(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class SurfaceData3Dd:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, position: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], normal: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"], var_position: typing.SupportsFloat | typing.SupportsIndex, var_normal: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def normal(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @normal.setter
    def normal(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @property
    def position(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float64], "[3, 1]"]:
        ...
    @position.setter
    def position(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]) -> None:
        ...
    @property
    def var_normal(self) -> float:
        ...
    @var_normal.setter
    def var_normal(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def var_position(self) -> float:
        ...
    @var_position.setter
    def var_position(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class SurfaceData3Df:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, position: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"], normal: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"], var_position: typing.SupportsFloat | typing.SupportsIndex, var_normal: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def normal(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"]:
        ...
    @normal.setter
    def normal(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"]) -> None:
        ...
    @property
    def position(self) -> typing.Annotated[numpy.typing.NDArray[numpy.float32], "[3, 1]"]:
        ...
    @position.setter
    def position(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32, "[3, 1]"]) -> None:
        ...
    @property
    def var_normal(self) -> float:
        ...
    @var_normal.setter
    def var_normal(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    @property
    def var_position(self) -> float:
        ...
    @var_position.setter
    def var_position(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class SurfaceDataManager2Dd(SurfaceDataManager2DdBase):
    pass
class SurfaceDataManager2DdBase:
    def __getitem__(self, index: typing.SupportsInt | typing.SupportsIndex) -> SurfaceData2Dd:
        ...
    def __init__(self) -> None:
        ...
    def add_entry(self, entry: SurfaceData2Dd) -> int:
        ...
    def clear(self) -> None:
        ...
    def remove_entry(self, index: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def reserve(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def size(self) -> int:
        ...
    @property
    def buffer(self) -> list[SurfaceData2Dd]:
        ...
class SurfaceDataManager2Df(SurfaceDataManager2DfBase):
    pass
class SurfaceDataManager2DfBase:
    def __getitem__(self, index: typing.SupportsInt | typing.SupportsIndex) -> SurfaceData2Df:
        ...
    def __init__(self) -> None:
        ...
    def add_entry(self, entry: SurfaceData2Df) -> int:
        ...
    def clear(self) -> None:
        ...
    def remove_entry(self, index: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def reserve(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def size(self) -> int:
        ...
    @property
    def buffer(self) -> list[SurfaceData2Df]:
        ...
class SurfaceDataManager3Dd(SurfaceDataManager3DdBase):
    pass
class SurfaceDataManager3DdBase:
    def __getitem__(self, index: typing.SupportsInt | typing.SupportsIndex) -> SurfaceData3Dd:
        ...
    def __init__(self) -> None:
        ...
    def add_entry(self, entry: SurfaceData3Dd) -> int:
        ...
    def clear(self) -> None:
        ...
    def remove_entry(self, index: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def reserve(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def size(self) -> int:
        ...
    @property
    def buffer(self) -> list[SurfaceData3Dd]:
        ...
class SurfaceDataManager3Df(SurfaceDataManager3DfBase):
    pass
class SurfaceDataManager3DfBase:
    def __getitem__(self, index: typing.SupportsInt | typing.SupportsIndex) -> SurfaceData3Df:
        ...
    def __init__(self) -> None:
        ...
    def add_entry(self, entry: SurfaceData3Df) -> int:
        ...
    def clear(self) -> None:
        ...
    def remove_entry(self, index: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def reserve(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def size(self) -> int:
        ...
    @property
    def buffer(self) -> list[SurfaceData3Df]:
        ...
class YamlableBase:
    def __str__(self) -> str:
        ...
    def as_yaml_file(self, yaml_file: str) -> None:
        ...
    def as_yaml_string(self) -> str:
        ...
    def from_command_line(self, args: collections.abc.Sequence[str]) -> bool:
        ...
    def from_yaml_file(self, yaml_file: str, base_config_field: str) -> bool:
        ...
    def from_yaml_string(self, yaml_str: str) -> bool:
        ...
kExternal: SignMethod  # value = <SignMethod.kExternal: 3>
kHybrid: SignMethod  # value = <SignMethod.kHybrid: 4>
kNone: SignMethod  # value = <SignMethod.kNone: 0>
kNormalGp: SignMethod  # value = <SignMethod.kNormalGp: 2>
kSignGp: SignMethod  # value = <SignMethod.kSignGp: 1>
