test_query:
    default_invalid_sdf: -1
    max_test_valid_distance_var: 0.02
    search_area_half_size: 4
    num_neighbor_gps: 8
    use_smallest: true
    compute_gradient: true  # whether to compute gradient
    compute_gradient_variance: true  # whether to compute gradient variance
    compute_covariance: false  # whether to compute covariance
    use_gp_covariance: false
    retrain_outdated: true  # whether to retrain the trained but outdated GPs
    use_global_buffer: true  # whether to use the global buffer for test queries
num_threads: 64
update_hz: 60
sensor_noise: 0.001
gp_sdf_area_scale: 5
max_valid_gradient_var: 0.1
invalid_position_var: 2.0
sdf_gp:
    sign_method: "kSignGp"  # "kSignGp", "kNormalGp", "kExternal", "kHybrid", "kNone"
    hybrid_sign_methods: [ "kSignGp", "kExternal" ]
    hybrid_sign_threshold: 0.18  # > sqrt(3) * tree_resolution
    normal_scale: 50.0
    softmin_temperature: 10.0
    sign_gp_offset_distance: -0.2 # <=0, when it is 0.0, the sign GP relies on the gradients only
    edf_gp_offset_distance: 0.0   # >=0, e.g. 0.015 will cause a shell of thickness 0.03 behind the surface
    sign_gp:
        kernel_type: erl::covariance::Matern32<float, 3>
        kernel_setting_type: erl::covariance::Covariance<float>::Setting
        kernel:
            x_dim: 3
            scale: 0.05
            scale_mix: 1
            weights: [ ]
        max_num_samples: 48   # max dataset size
        no_gradient_observation: false
    edf_gp:
        kernel_type: erl::covariance::Matern32<float, 3>
        kernel_setting_type: erl::covariance::Covariance<float>::Setting
        kernel:
            x_dim: 3
            scale: 0.043  # sqrt(3) / log_lambda, will be overridden by log_lambda
            scale_mix: 1
            weights: [ ]
        log_lambda: 40
        duplicate_epsilon: 0.0
        max_num_samples: 96   # max dataset size
        no_gradient_observation: true
