__base__: ../../common/sdf_mapping_float.yaml
test_query:
    max_test_valid_distance_var: 1
    search_area_half_size: 4
    num_neighbor_gps: 6
    compute_gradient_variance: true
    compute_covariance: true
    max_num_retrain_gps: 100
min_num_gps_to_update: 256
gp_sdf_area_scale: 4
max_valid_gradient_var: 0.1
invalid_position_var: 0.25
sdf_gp:
    sign_method: "sign_gp"
    sign_gp_offset_distance: -0.1
    sign_gp:
        kernel_type: erl::covariance::Matern32<float, 2>
        kernel:
            x_dim: 2
            scale: 0.5
        max_num_samples: 256
    edf_gp:
        kernel_type: erl::covariance::Matern32<float, 2>
        kernel:
            x_dim: 2
        log_lambda: 20
        max_num_samples: 256
