max_x: 2
max_y: 2
min_x: -2
min_y: -2
radius: 1
num_surf_samples: 1000
add_off_surf_points: false
off_surf_grid_size: 51
test_num_x: 201
test_num_y: 201
var_x: 0.001
var_y: 0.001
gp:
    kernel_type: erl::covariance::Matern32<double, 2>
    kernel_setting_type: erl::covariance::Covariance<double>::Setting
    kernel:
        x_dim: 2
        scale: 1
        scale_mix: 1
        weights: [ ]
    max_num_samples: -1
    no_gradient_observation: true
    log_lambda: 40  # 200
output_dir: log_sdf_regression
