num_threads: 64
update_hz: 50
gp_sdf_area_scale: 3
offset_distance: 0.0
zero_gradient_threshold: 1.0e-6
max_valid_gradient_var: 0.1
invalid_position_var: 2
train_gp_immediately: false
gp_sdf:
  kernel:
    type: kMatern32
    x_dim: 2
    alpha: 1
    scale: 1.2
    scale_mix: 1
    weights:
      [ ]
  log_lambda: 40
  edf_threshold: 0.1
  max_num_samples: 256   # max dataset size
test_query:
  max_test_valid_distance_var: 0.4
  search_area_half_size: 2
  use_nearest_only: false
  compute_covariance: false  # whether to compute covariance
  recompute_variance: true
  softmax_temperature: 10
