num_threads: 64
update_hz: 50
gp_sdf_area_scale: 2
offset_distance: 0.0
zero_gradient_threshold: 9.9999999999999995e-07
max_valid_gradient_var: 0.10000000000000001
invalid_position_var: 2
train_gp_immediately: false
gp_sdf:
  kernel:
    type: kMatern32
    x_dim: 2
    alpha: 1
    scale: 1.2
    scale_mix: 1
    weights:
      []
  log_lambda: 40
  edf_threshold: 0.1
  max_num_samples: 256   # max dataset size
test_query:
  max_test_valid_distance_var: 0.40000000000000002
  search_area_half_size: 2
  use_nearest_only: false
