__base__: ../../common/bayesian_hilbert_surf_mapping_float.yaml
local_bhm:
    bhm:
        min_distance: 0.05
        max_distance: 30
        sampling_area_scale: 3.0
        free_points_per_meter: 3.0
        init_mu: 2.0
        sparse_zero_threshold: 0.005
    kernel_type: erl::covariance::RadialBiasFunction<float, 3>
    kernel:
        x_dim: 3
        scale: 0.015  # 0.017
    min_dataset_size: 10
    min_dataset_hit_size: 5
    max_dataset_size: 120
    hit_point_buffer_size: 256
    ray_buffer_size: 2048
    surface_grid_size: 8
ray_selector:
    azimuth_min: -0.79
    azimuth_max: 0.79
    elevation_min: -0.52
    elevation_max: 0.52
    num_azimuth_angles: 600
    num_elevation_angles: 340
    transform: # transform from optical frame to camera frame
        - [ 0, 0, 1, 0 ]
        - [ -1, 0, 0, 0 ]
        - [ 0, -1, 0, 0 ]
tree:
    resolution: 0.08  # 0.1
    log_odd_min: -10
    log_odd_max: 50
    log_odd_hit: 0.95
    log_odd_miss: -0.01
    log_odd_occ_threshold: 0
update_map:
    method: 2
    max_num_bhm: 1500
    max_num_voxels: 10000
scaling: 1.0
hinged_grid_size: 7
bhm_test_margin: 0.04 # 0.045
