__base__: ../../common/gp_occ_surf_mapping_float.yaml
sensor_gp:
    row_group_size: 8
    row_overlap_size: 4
    row_margin: &row_margin 1
    col_group_size: 8
    col_overlap_size: 4
    col_margin: &col_margin 1
    min_num_samples_per_group: 32
    sensor_range_var: 0.001
    sensor_frame_type: erl::geometry::LidarFrame3D<float>
    sensor_frame_setting_type: erl::geometry::LidarFrame3D<float>::Setting
    sensor_frame:
        row_margin: *row_margin
        col_margin: *col_margin
        valid_range_min: 0.06
        valid_range_max: 2.5
        azimuth_min: -3.1415926535897931
        azimuth_max: 3.1415926535897931
        elevation_min: -0.7853981633974483
        elevation_max: 0.7853981633974483
        num_azimuth_lines: 1024
        num_elevation_lines: 128
    gp:
        kernel_type: erl::covariance::OrnsteinUhlenbeck<float, 2>
        kernel:
            x_dim: 2
            scale: 1
        max_num_samples: 160
update_map_points:
    max_adjust_tries: 2
tree:
    resolution: 0.07
    log_odd_min: -10
    log_odd_max: 20
    log_odd_hit: 0.9
    log_odd_miss: -0.05
    log_odd_occ_threshold: 5
surface_resolution: 0.02
perturb_delta: 0.05
scaling: 0.1
