__base__: ../../common/sdf_mapping_float.yaml
test_query:
    search_area_half_size: 5
    num_neighbor_gps: 8
    max_num_retrain_gps: 512
min_num_gps_to_update: 1024
update_hz: 10
gp_sdf_area_scale: 8
sdf_gp:
    sign_method: "sign_gp"
    normal_scale: 50.0
    sign_gp_offset_distance: -0.2  # <=0, when it is 0.0, the sign GP relies on the gradients only
    edf_gp_offset_distance: 0.0    # >=0, e.g. 0.015 will cause a shell of thickness 0.03 behind the surface
    sign_gp:
        kernel_type: erl::covariance::Matern32<float, 3>
        kernel:
            x_dim: 3
            scale: 0.05
        max_num_samples: 48
        no_gradient_observation: false
    edf_gp:
        kernel_type: erl::covariance::Matern32<float, 3>
        log_lambda: 40
        max_num_samples: 128
