__base__: ../common/gp_occ_surf_mapping_float.yaml
sensor_gp:
    row_group_size: 6
    row_overlap_size: 2
    row_margin: &row_margin 1
    col_group_size: 6
    col_overlap_size: 2
    col_margin: &col_margin 1
    min_num_samples_per_group: 18
    sensor_range_var: 0.01
    sensor_frame_type: erl::geometry::DepthFrame3D<float>
    sensor_frame_setting_type: erl::geometry::DepthFrame3D<float>::Setting
    sensor_frame:
        row_margin: *row_margin
        col_margin: *col_margin
        valid_range_min: 0.4
        valid_range_max: 4
        camera_intrinsic:
            image_height: 480
            image_width: 640
            camera_fx: 525
            camera_fy: 525
            camera_cx: 319.5
            camera_cy: 239.5
    gp:
        kernel_type: erl::covariance::OrnsteinUhlenbeck<float, 2>
        kernel:
            x_dim: 2
            scale: 0.5
        max_num_samples: 40
tree:
    resolution: 0.2
    log_odd_min: -5
    log_odd_max: 5
    log_odd_hit: 0.4
    log_odd_miss: -0.4
    log_odd_occ_threshold: 0
surface_resolution: 0.04
perturb_delta: 0.01
