__base__: ../common/bayesian_hilbert_surf_mapping_float.yaml
local_bhm:
    bhm:
        min_distance: 0.06
        max_distance: 2.5
        sampling_area_scale: 3.0
        free_points_per_meter: 2.6
    kernel:
        x_dim: 3
        scale: 0.016
    min_dataset_size: 64
    min_dataset_hit_size: 48
    max_dataset_size: 200
    hit_point_buffer_size: 32
    ray_buffer_size: 1024
    surface_grid_size: 7
ray_selector:
    azimuth_min: -3.1415926535897931
    azimuth_max: 3.1415926535897931
    elevation_min: -0.7853981633974483
    elevation_max: 0.78539816339744830
    num_azimuth_angles: 1024
    num_elevation_angles: 128
    transform:
        - [ 1, 0, 0, 0 ]
        - [ 0, 1, 0, 0 ]
        - [ 0, 0, 1, 0 ]
tree:
    resolution: 0.07 # 0.06 # 0.075
    log_odd_min: -10
    log_odd_max: 20
    log_odd_hit: 0.9
    log_odd_miss: -0.05
    log_odd_occ_threshold: 5
update_map:
    method: 2
    max_num_bhm: 1500
    max_num_voxels: 10000
scaling: 0.1
hinged_grid_size: 7
bhm_overlap: 0.05
bhm_test_margin: 0.06
