local_bhm:
    bhm:
        diagonal_sigma: true
        min_distance: 0.6
        max_distance: 35.0
        free_points_per_meter: 0.5
        free_sampling_margin: 0.001
        init_mu: 0.0
        init_sigma: 10000
        num_em_iterations: 2
        sparse_zero_threshold: 1.0e-3
        use_sparse: true
    kernel_type: erl::covariance::RadialBiasFunction<float, 3>
    kernel_setting_type: erl::covariance::Covariance<float>::Setting
    kernel:
        x_dim: 3
        scale: 0.3 # 0.16 # 0.25
        scale_mix: 1
        weights: []
    min_dataset_size: 20
    max_dataset_size: 3000
    hit_buffer_size: 0
    surface_resolution: 0.3
ray_selector:
    azimuth_min: -3.1415926535897931
    azimuth_max: 3.1415926535897931
    elevation_min: -0.7853981633974483
    elevation_max: 0.7853981633974483
    num_azimuth_angles: 1024
    num_elevation_angles: 128
    transform:
        - [1, 0, 0, 0]
        - [0, 1, 0, 0]
        - [0, 0, 1, 0]
tree:
    resolution: 1.8 # 0.5 # 1.0 # 2.0
    tree_depth: 16
    log_odd_min: -3
    log_odd_max: 100
    log_odd_hit: 10
    log_odd_miss: -0.1
    log_odd_occ_threshold: 0
    use_change_detection: false
    use_aabb_limit: false
    aabb:
        center: [0, 0, 0]
        half_sizes: [0, 0, 0]
update_map:
    surface_max_abs_logodd: 2
    surface_bad_abs_logodd: 200
    surface_step_size: 0.001
    max_num_points: 50000
    max_adjust_tries: 1
    var_scale: 0.01
    var_max: 1.5
    update_with_cuda: false
    cuda_device_id: 0
    update_batch_size: 512
scaling: 1.0
hinged_grid_size: 5 # 5 # 7
bhm_depth: 16 # 15 # 16
bhm_overlap: 0.8 # 0.4 # 0.8
build_bhm_on_hit: true
faster_prediction: true
bhm_test_margin: 0.75 # 0.3 # 0.7
test_knn: 1
test_batch_size: 1000
